### ISSUE TITLE
context is getting overridden

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-mobile-views#1]
with the plugin enabled, I just get `__isMobile: false` in the view context

**Comment by dawnerd** [comment]
Same issue we originally had: https://github.com/firstandthird/hapi-view-context/issues/8

I think we might have to write a plugin that you register onPreResponse calls to and it calls them all before taking over the view.

**Comment by jgallen23** [comment]
when I was testing, it wasn't taking over the view, it was just loading the normal view.

For now, just expose a method that you'll manually call to and then it hooks into onPreResponse so we can control that it's the last one.

Another option, which I just found, is there is an after call that you can make sure the plugin runs after others:
http://hapijs.com/api#serverextevents

`after - a string or array of strings of plugin names this method must execute after (on the same event). Otherwise, extension methods are executed in the order added.`

**Comment by jgallen23** [comment]
for hapi-view-context, I'm thinking we need to go back to exposing a function that gets called and then hapi-view-context does the ext('onPreResponse' and then calls that function.  Thoughts?
